language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

before_script:
  - cd angular-src
  - npm install -g @angular/cli
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


script:
  - pwd
  - ls
  - npm test