language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - cd $TRAVIS_BUILD_DIR/angular-src

script:
  - pwd
  - ls
  - npm test