language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

env:
  - HOME="/home/travis/build/abhioshar/travistest/angular-src"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - pwd
  - cd angular-src
  - pwd

install:
  - pwd
  - npm install -g @angular/cli
  - pwd
  - npm install
  - pwd

script:
  - pwd
  - ls
  - npm test