language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

env:
  global:
    - HOME=`pwd`/angular-src
    - NODE_ENV=travisci
    - BUILD_DIR=`pwd`/angular-src

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - pwd
  - cd angular-src
  - pwd

install:
  - pwd
  - npm install -g @angular/cli
  - pwd
  - npm install
  - pwd

script:
  - pwd
  - ls
  - npm test