language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - pwd
  - cd angular-src
  - pwd

install:
  - pwd
  - npm install -g @angular/cli
  - pwd
  - npm install --prefix ./angular-src
  - npm install
  - pwd
  - ng build

script:
  - pwd
  - ls
  - karma start angular-src/karma.conf.js