language: node_js
node_js: 
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd angular-src

before_install:
  - cd angular-src

script:
  - ng test --watch=false